apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.taxayp.com/taxayp/K8s-HomeLab-Gitops.git'
    targetRevision: HEAD
    path: infrastructure
    directory:
      recurse: true  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.taxayp.com/taxayp/K8s-HomeLab-Gitops.git'
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true