apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: master
    path: deploy/chart/local-path-provisioner
    helm:
      values: |
        storageClass:
          defaultClass: false
          name: local-path
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /opt/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
