apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: default
  source:
    # 1. Point to the ACTUAL GitHub Repo
    repoURL: https://github.com/rancher/local-path-provisioner.git
    # 2. Use 'master' (This is the branch Rancher uses)
    targetRevision: master
    # 3. Path to where the Chart.yaml lives in their repo
    path: deploy/chart/local-path-provisioner
    helm:
      values: |
        storageClass:
          name: local-path
          defaultClass: false
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /opt/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
