apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: longhorn-system 
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-role"  

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-secret-sync
  namespace: longhorn-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: aws-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: longhorn-aws
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: longhorn-aws
        property: AWS_SECRET_ACCESS_KEY