apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportsodds
  namespace: sportsodds
  labels:
    app: sportsodds
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportsodds
  template:
    metadata:
      labels:
        app: sportsodds
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: sportsodds
          image: registry.taxayp.com/taxayp/sportsodds:9d53aa2c
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sportsodds-pg-app
                  key: uri
          envFrom:
            - secretRef:
                name: sportsodds-secrets  
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /api/cache-bust
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/cache-bust
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
