apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.5.14
    helm:
      values: |
        helm:
      values: |
        configs:
          params:
            server.insecure: true
          secret:
            argocdServerAdminPassword: "MyNewSecurePassword123"
        fullnameOverride: "argocd" 
        controller:
          replicas: 1
        server:
          replicas: 1
        repoServer:
          replicas: 1
        applicationSet:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
