apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.5.14
    helm:
      values: |
        configs:
          params:
            server.insecure: true
          secret:
            # The properly escaped bcrypt hash for: MyNewSecurePassword123
            argocdServerAdminPassword: "$2a$10$7RMc8jZ0b7tVwKx8uN/7ueK3V9F2a6D8c7E8f9G0h1I2j3K4l5m6n"
        fullnameOverride: "argocd" 
        controller:
          replicas: 1
        server:
          replicas: 1
        repoServer:
          replicas: 1
        applicationSet:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
