apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argocd
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-role"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-sync
  namespace: argocd
spec:
  refreshInterval: "1m" 
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: "Merge"
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: "admin.password"
      remoteRef:
        key: "argocd"                
        property: "admin.password"   
