apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oddsjunction
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  source:
    repoURL: 'https://gitlab.taxayp.com/taxayp/K8s-HomeLab-Gitops'
    targetRevision: main
    path: apps/oddsjunction
  destination:
    server: https://kubernetes.default.svc
    namespace: oddsjunction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
