apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgres-new
  namespace: gitea
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3

  storage:
    size: 5Gi
    storageClass: longhorn

  enablePDB: true
  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      encoding: UTF8
      localeCType: C
      localeCollate: C
      secret:
        name: gitea-db-secrets

  backup:
    target: prefer-standby
    barmanObjectStore:
      destinationPath: "s3://my-longhorn-backups-syd/backups/postgres/"        
      s3Credentials:
        accessKeyId:
          key: AWS_ACCESS_KEY_ID
          name: gitea-db-secrets
        secretAccessKey:
          key: AWS_SECRET_ACCESS_KEY
          name: gitea-db-secrets
      wal:
        compression: gzip

