apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 10.2.0
    helm:
      values: |
        # 1. Turn off ALL chart-injected sub-databases completely
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: false
        redis-cluster:
          enabled: false

        # 2. Configure Gitea to look at our custom lightweight Postgres deployment below
        gitea:
          config:
            APP_NAME: "Patel Homelab Git Core"
            RUN_MODE: prod
            database:
              DB_TYPE: postgres
              HOST: "gitea-postgres-service:5432"
              NAME: "gitea"
              USER: "gitea"
          admin:
            username: taxayp
            password:
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: admin-password

        # 3. Storage for Gitea's repositories
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 15Gi
          accessModes:
            - ReadWriteOnce

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true