apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: gitea
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-role"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-vault-secrets
  namespace: gitea
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitea-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: gitea
        property: db-password
    - secretKey: username
      remoteRef:
        key: gitea
        property: username
    - secretKey: password
      remoteRef:
        key: gitea
        property: password