apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-postgres-service
  namespace: gitea
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gitea-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgres
  template:
    metadata:
      labels:
        app: gitea-postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:16.3
          env:
            - name: POSTGRES_DB
              value: "gitea"
            - name: POSTGRES_USER
              value: "gitea"
            # Crucial: Instructs Postgres to initialize in a clean subfolder away from lost+found
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: db-password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: gitea-postgres-pvc